version: 2.1

jobs:
  deploy-prod:
    docker:
      - image: node:18.7.0
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: ssh -o StrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_project.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-prod:
          filters:
            branches:
              only:
                - dev
