import { PATH_DASHBOARD } from "../routes/paths";

export const staticCardData = [
    {
      color: "#0EB10A",
      title: "States Assessed",
      icon: 'wallet',
      value: 0,
      sub: 0,
      classname: "card-greenish",
      subTitle: "Number of states receiving DFF Disbursements from NPHCDA",
      showFCT: true,
      show: false,
      isString: true,
      path: PATH_DASHBOARD.m_and_e.state,
    }, 
    {
      color: "#00A8BF",
      title: "LGAs Assessed",
      icon: 'tree-structure',
      value: 0,
      classname: "card-goldish",
      subTitle: "State where all LGAs have at least 1 Functional SHC benefitting from BHCPF",
      sub: 0,
      showFCT: true,
      show: false,
      isString: true,
      path: PATH_DASHBOARD.m_and_e.lga,
    },
    {
      color: "#0A57B1",
      title: "HFs Assessed",
      icon: 'tree-struct',
      value: 0,
      classname: "card-blueish",
      sub: 0,
      showFCT: false,
      subTitle: "State where all wards have at least 2 functional PHC benefitting from BHCPF",
      show: false,
      isString: true,
      path: PATH_DASHBOARD.m_and_e.hf,
    },
    {
      color: "#B90651",
      title: "HFs Assessed",
      icon: 'box',
      value: 0,
      classname: "card-blueish",
      sub: 0,
      showFCT: false,
      subTitle: "Proportion of State that paid 25% counterpart fund for BHCPF",
      show: false,
      isString: true,
      path: PATH_DASHBOARD.m_and_e.hf,
    },
  ];
