import { PATH_DASHBOARD } from "../routes/paths";

export const staticCardData = [
    {
      color: "#0EB10A",
      title: "States Assessed",
      icon: 'wallet',
      value: null,
      sub: 0,
      classname: "card-greenish",
      subTitle: "States that have provided annual 25% counterpart funding for BHCPF",
      showFCT: true,
      show: false,
      isString: true,
      path: PATH_DASHBOARD.m_and_e.state,
    }, 
    {
      color: "#00A8BF",
      title: "LGAs Assessed",
      icon: 'tree-structure',
      value: null,
      classname: "card-goldish",
      subTitle: "States with functional Coordination platforms established at state level",
      sub: 0,
      showFCT: true,
      show: false,
      isString: true,
      path: PATH_DASHBOARD.m_and_e.lga,
    },
    {
      color: "#0A57B1",
      title: "HFs Assessed",
      icon: 'tree-struct',
      value: null,
      classname: "card-blueish",
      sub: 0,
      showFCT: false,
      subTitle: "SPHCBs that received authorization to disburse DFF to PHC",
      show: false,
      isString: true,
      path: PATH_DASHBOARD.m_and_e.hf,
    },
    {
      color: "#B90651",
      title: "HFs Assessed",
      icon: 'box',
      value: null,
      classname: "card-blueish",
      sub: 0,
      showFCT: false,
      subTitle: "PHCs with functional WDCs",
      show: false,
      isString: true,
      path: PATH_DASHBOARD.m_and_e.hf,
    },
  ];
