export const AllIndicators = [
    {
        "id": "1e8af63c80f642aba33e08c8523b8a8c",
        "name": "States that have provided annual 25% counterpart funding for BHCPF",
        "group": "Governance",
        "groupKey": "governance",
        "completed": false,
        "indicatorNo": "indicator1",
        "indicatorNational": "indicator1National",
        "indicatorState": "indicator1State",
        "indicatorlga": "indicator1Lga",
        "shortName": "State Support Funding"
    },
    {
        "id": "ffbe3c2ff4da4e6e8e7b56be0f075901",
        "name": "States with functional Coordination platforms established at state level",
        "group": "Governance",
        "groupKey": "governance",
        "completed": false,
        "indicatorNo": "indicator2",
        "indicatorNational": "indicator2National",
        "indicatorState": "indicator2State",
        "indicatorlga": "indicator2Lga",
        "shortName": "State Coordination Platforms"
    },
    {
        "id": "06153b0879ee4000a9947583556acdb2",
        "name": "LGAs with functional Coordination platforms established",
        "group": "Governance",
        "groupKey": "governance",
        "completed": false,
        "indicatorNo": "indicator3",
        "indicatorNational": "indicator3National",
        "indicatorState": "indicator3State",
        "indicatorlga": "indicator3Lga",
        "shortName": "LGA Coordination Platforms"
    },
    {
        "id": "073fb44d07e3454598175b5d52d564a4",
        "name": "PHCs with functional Coordination platforms established",
        "group": "Governance",
        "groupKey": "governance",
        "completed": false,
        "indicatorNo": "indicator4",
        "indicatorNational": "indicator4National",
        "indicatorState": "indicator4State",
        "indicatorlga": "indicator4Lga",
        "shortName": "PHCs Coordination Platforms"
    },
    {
        "id": "74dbee51d38044f6b8395961c3d33f32",
        "name": "SPHCBs receiving quarterly allocation from  NPHCDA",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator5",
        "indicatorNational": "indicator5National",
        "indicatorState": "indicator5State",
        "indicatorlga": "indicator5Lga",
        "shortName": "SPHCBs Receiving Quarterly Allocation"
    },
    {
        "id": "29a3895bc04b49fe9ed22c3e6309abd7",
        "name": "PHCs that submitted Quarterly business plans for disbursement",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator6",
        "indicatorNational": "indicator6National",
        "indicatorState": "indicator6State",
        "indicatorlga": "indicator6Lga",
        "shortName": "PHCs that Submitted Quarterly Business Plans"
    },
    {
        "id": "73398862771b483ea343102193d485a9",
        "name": "PHCs receiving quarterly allocation from  SPHCB.",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator7",
        "indicatorNational": "indicator7National",
        "indicatorState": "indicator7State",
        "indicatorlga": "indicator7Lga",
        "shortName": "PHCs Receiving Quarterly Allocation"
    },
    {
        "id": "66a9e011b8024fd7914e17e422fb37f9",
        "name": "SPHCBs submitting complete retirement documents to NPHCDA on time",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator8",
        "indicatorNational": "indicator8National",
        "indicatorState": "indicator8State",
        "indicatorlga": "indicator8Lga",
        "shortName": "SPHCBs Submitting Complete Retirement"
    },
    {
        "id": "0597501ba5aa49288d8a9edc84ba1d16",
        "name": "SPHCBs that received authorization to disburse DFF to PHC",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator9",
        "indicatorNational": "indicator9National",
        "indicatorState": "indicator9State",
        "indicatorlga": "indicator9Lga",
        "shortName": "SPHCBs with Authorization to Disburse DFF"
    },
    {
        "id": "644ad76c730d4714a02e8d7311d86325",
        "name": "PHCs submitting complete retirement documents to LGA",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator10",
        "indicatorNational": "indicator10National",
        "indicatorState": "indicator10State",
        "indicatorlga": "indicator10Lga",
        "shortName": "PHCs Submitting Complete Retirement"
    },
    {
        "id": "502462f19a144f2dac2bfe9d210f0f51",
        "name": "LGA submitting complete retirement documents to SPHCBs",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator11",
        "indicatorNational": "indicator11National",
        "indicatorState": "indicator11State",
        "indicatorlga": "indicator11Lga",
        "shortName": "LGAs submitting Complete Retirement"
    },
    {
        "id": "89820d2397314035af16fd29f9e6d915",
        "name": "BHCPF spendings  (on drugs, equipment, HR, community outreach and infrastructure upgrades) at the HF level",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator12",
        "indicatorNational": "indicator12National",
        "indicatorState": "indicator12State",
        "indicatorlga": "indicator12Lga",
        "shortName": "BHCPF Spendings at Health Facility Level"
    },
    {
        "id": "3d1d48cb41d14507b1faa11dbb04e854",
        "name": "PHCs with single bank account",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator13",
        "indicatorNational": "indicator13National",
        "indicatorState": "indicator13State",
        "indicatorlga": "indicator13Lga",
        "shortName": "PHCs with Single Bank Account"
    },
    {
        "id": "185c9fddd74f4b60a52b7e09056ba067",
        "name": "PHCs that have received BHCPF BMPHS capitation",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator14",
        "indicatorNational": "indicator14National",
        "indicatorState": "indicator14State",
        "indicatorlga": "indicator14Lga",
        "shortName": "Received BHCPF BMPHS Capitation"
    },
    {
        "id": "ea9428e22ea44c39abe84d399f95b8a4",
        "name": "PHCs that have received funds from other state insurance program",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator15",
        "indicatorNational": "indicator15National",
        "indicatorState": "indicator15State",
        "indicatorlga": "indicator15Lga",
        "shortName": "Received Funds from Other State Insurance Program"
    },
    {
        "id": "4d4ec80c66cc46c2bf485a7bf81759e6",
        "name": "SPHCBs with partners supporting BHCPF",
        "group": "Finance",
        "groupKey": "finance",
        "completed": false,
        "indicatorNo": "indicator16",
        "indicatorNational": "indicator16National",
        "indicatorState": "indicator16State",
        "indicatorlga": "indicator16Lga",
        "shortName": "SPHCBs with partners supporting BHCPF"
    },
    {
        "id": "ebe27e321fd14b51a60e85fb182ebfbc",
        "name": "PHCs with stockout of essential (tracer) drugs  within the quarter under review",
        "group": "Essential Medicine",
        "groupKey": "essentialMed",
        "completed": false,
        "indicatorNo": "indicator17",
        "indicatorNational": "indicator17National",
        "indicatorState": "indicator17State",
        "indicatorlga": "indicator17Lga",
        "shortName": "Stockout of Essential (tracer) Drugs"
    },
    {
        "id": "ed78c5cbce3c4333b5a70310f6dffd85",
        "name": "BHCPF PHCs purchasing essential drugs/medicine from DMA or accredited pharmacy",
        "group": "Essential Medicine",
        "groupKey": "essentialMed",
        "completed": false,
        "indicatorNo": "indicator18",
        "indicatorNational": "indicator18National",
        "indicatorState": "indicator18State",
        "indicatorlga": "indicator18Lga",
        "shortName": "Purchasing Essential Drugs from DMA/Accredited Pharmacy"
    },
    {
        "id": "d0d4bdf9103e43058368daa567d48000",
        "name": "PHCs that received essential drugs donation from other sources",
        "group": "Essential Medicine",
        "groupKey": "essentialMed",
        "completed": false,
        "indicatorNo": "indicator19",
        "indicatorNational": "indicator19National",
        "indicatorState": "indicator19State",
        "indicatorlga": "indicator19Lga",
        "shortName": "Received Drugs Donations From Other Sources"
    },
    {
        "id": "2ea1ee0864cc41d8aa78abdc8cc44ab2",
        "name": "BHCPF health facilities with minimum of two (2) midwives deployed by SPHCB/LGA",
        "group": "Human Resources",
        "groupKey": "hr",
        "completed": false,
        "indicatorNo": "indicator20",
        "indicatorNational": "indicator20National",
        "indicatorState": "indicator20State",
        "indicatorlga": "indicator20Lga",
        "shortName": "Midwives >= 2"
    },
    {
        "id": "34ff943efca343a4b932c670f456720f",
        "name": "BHCPF health facilities with minimum of two (2) CHEW deployed by SPHCB/LGA",
        "group": "Human Resources",
        "groupKey": "hr",
        "completed": false,
        "indicatorNo": "indicator21",
        "indicatorNational": "indicator21National",
        "indicatorState": "indicator21State",
        "indicatorlga": "indicator21Lga",
        "shortName": "CHEW >= 2"
    },
    {
        "id": "ac474c724e364b688b6cb55f235e204c",
        "name": "BHCPF HFs that engaged adhoc staff with DFF",
        "group": "Human Resources",
        "groupKey": "hr",
        "completed": false,
        "indicatorNo": "indicator22",
        "indicatorNational": "indicator22National",
        "indicatorState": "indicator22State",
        "indicatorlga": "indicator22Lga",
        "shortName": "HF Engaging Adhoc Staff"
    },
    {
        "id": "d83518688274479bae22504092a91dbe",
        "name": "states engaging adhoc midwives with the 5% HRH BHCPF allocation",
        "group": "Human Resources",
        "groupKey": "hr",
        "completed": false,
        "indicatorNo": "indicator23",
        "indicatorNational": "indicator23National",
        "indicatorState": "indicator23State",
        "indicatorlga": "indicator23Lga",
        "shortName": "State Adhoc Midwives"
    },
    {
        "id": "83c18ee0a717430cbff395c5076e63a3",
        "name": "wards that have CHIPS agent deployed per state",
        "group": "Human Resources",
        "groupKey": "hr",
        "completed": false,
        "indicatorNo": "indicator24",
        "indicatorNational": "indicator24National",
        "indicatorState": "indicator24State",
        "indicatorlga": "indicator24Lga",
        "shortName": "Wards with CHIPS Agents"
    },
    {
        "id": "2a7a993272944428ad43199194903e86",
        "name": "PHCs submitting NHMIS data",
        "group": "Health Information Systems",
        "groupKey": "his",
        "completed": false,
        "indicatorNo": "indicator25",
        "indicatorNational": "indicator25National",
        "indicatorState": "indicator25State",
        "indicatorlga": "indicator25Lga",
        "shortName": "PHCs Submitting NHMIS Data"
    },
    // {
    //     "id": "e54d592fe9ef479eae62a3b4f4651c09",
    //     "name": "PHCs that carried out infrastructural repairs or upgrades with BHCPF",
    //     "group": "Infrastructure & Equipment",
    //     "groupKey": "ie",
    //     "completed": false,
    //     "indicatorNo": "indicator26",
    //     "indicatorNational": "indicator26National",
    //     "indicatorState": "indicator26State",
    //     "indicatorlga": "indicator26Lga",
    //     "shortName": "Carried out Infrastructural Repairs/Upgrades"
    // },
    // {
    //     "id": "877eb6c4a6b84a72ba9d8de17790f8f0",
    //     "name": "PHCs that purchased essential and basic equipment with BHCPF",
    //     "group": "Infrastructure & Equipment",
    //     "groupKey": "ie",
    //     "completed": false,
    //     "indicatorNo": "indicator27",
    //     "indicatorNational": "indicator27National",
    //     "indicatorState": "indicator27State",
    //     "indicatorlga": "indicator27Lga",
    //     "shortName": "Purchased Essential and Basic Equipment"
    // },
    // {
    //     "id": "44247e3938da4d9d9da158174e983c41",
    //     "name": " BHCPF facilities providing BMPHS",
    //     "group": "Service Selection & Design",
    //     "groupKey": "ssd",
    //     "completed": false,
    //     "indicatorNo": "indicator28",
    //     "indicatorNational": "indicator28National",
    //     "indicatorState": "indicator28State",
    //     "indicatorlga": "indicator28Lga",
    //     "shortName": "Providing BMPHS"
    // },
    // {
    //     "id": "ce70065a913c49c1b13cf48d60b64689",
    //     "name": "BHCPF facilities currently accredited for NHIA gateway operations",
    //     "group": "Service Selection & Design",
    //     "groupKey": "ssd",
    //     "completed": false,
    //     "indicatorNo": "indicator29",
    //     "indicatorNational": "indicator29National",
    //     "indicatorState": "indicator29State",
    //     "indicatorlga": "indicator29Lga",
    //     "shortName": "Accredited for NHIA Gateway Operations"
    // },
    // {
    //     "id": "9182bda7e2234508af08fd0c909bc11a",
    //     "name": "Trend of service utilization data on the DHIS2 Platform",
    //     "group": "Service Selection & Design",
    //     "groupKey": "ssd",
    //     "completed": false,
    //     "indicatorNo": "indicator30",
    //     "indicatorNational": "indicator30National",
    //     "indicatorState": "indicator30State",
    //     "indicatorlga": "indicator30Lga",
    //     "shortName": "Trend of service utilization data on the DHIS2 Platform"
    // },
    {
        "id": "7281b59d442448918ec9a8500ab6b6c3",
        "name": "planned supervisory visits conducted by State/LGA team",
        "group": "Supervision & Facility Management",
        "groupKey": "supervision",
        "completed": false,
        "indicatorNo": "indicator31",
        "indicatorNational": "indicator31National",
        "indicatorState": "indicator31State",
        "indicatorlga": "indicator31Lga",
        "shortName": "Planned Supervisory visits Conducted"
    },
    {
        "id": "96edaa0b69ff4d2090c6f88b93bfe2e0",
        "name": "PHCs visited by State/LGHA team for supportive supervision",
        "group": "Supervision & Facility Management",
        "groupKey": "supervision",
        "completed": false,
        "indicatorNo": "indicator32",
        "indicatorNational": "indicator32National",
        "indicatorState": "indicator32State",
        "indicatorlga": "indicator32Lga",
        "shortName": "PHCs Visited by State/LGHA Team"
    },
    {
        "id": "e5016546109d4500a8ccb6bfce0d95a1",
        "name": "planned supervisory visits conducted by State CHIPS-PIU",
        "group": "Supervision & Facility Management",
        "groupKey": "supervision",
        "completed": false,
        "indicatorNo": "indicator33",
        "indicatorNational": "indicator33National",
        "indicatorState": "indicator33State",
        "indicatorlga": "indicator33Lga",
        "shortName": "Supervisory Visits Conducted by State CHIPS-PIU"
    },
    {
        "id": "05ba77676d814a97a8418dbbc0b900f7",
        "name": "States that conducted sensitization and awareness creation services",
        "group": "Community Linkages",
        "groupKey": "cl",
        "completed": false,
        "indicatorNo": "indicator34",
        "indicatorNational": "indicator34National",
        "indicatorState": "indicator34State",
        "indicatorlga": "indicator34Lga",
        "shortName": "States that Conducted Sensitization and Awareness Creation Services"
    },
    {
        "id": "5c0be05ba44942f29c8b8731fe296265",
        "name": "PHCs that conduct sensitization and awareness creation services",
        "group": "Community Linkages",
        "groupKey": "cl",
        "completed": false,
        "indicatorNo": "indicator35",
        "indicatorNational": "indicator35National",
        "indicatorState": "indicator35State",
        "indicatorlga": "indicator35Lga",
        "shortName": "PHCs that Conduct Sensitization and Awareness Creation Services"
    },
    {
        "id": "f46f514d9f6d4d4fa017af607127141e",
        "name": "PHCs with functional WDCs",
        "group": "Community Linkages",
        "groupKey": "cl",
        "completed": false,
        "indicatorNo": "indicator36",
        "indicatorNational": "indicator36National",
        "indicatorState": "indicator36State",
        "indicatorlga": "indicator36Lga",
        "shortName": "PHCs with Functional WDCs"
    },
    {
        "id": "bee6a73c214f4de7908c77e3a6e5eab5",
        "name": "BHCPF facilities where quality assessment was conducted.",
        "group": "Quality Improvement",
        "groupKey": "qa",
        "completed": false,
        "indicatorNo": "indicator37",
        "indicatorNational": "indicator37National",
        "indicatorState": "indicator37State",
        "indicatorlga": "indicator37Lga",
        "shortName": "Quality Assessment Conducted"
    },
    {
        "id": "3b81421bee2e4467835e5c53193ae51e",
        "name": "PHCs that completed at least 50% of the activities in their business plan.",
        "group": "Quality Improvement",
        "groupKey": "qa",
        "completed": false,
        "indicatorNo": "indicator38",
        "indicatorNational": "indicator38National",
        "indicatorState": "indicator38State",
        "indicatorlga": "indicator38Lga",
        "shortName": "Completed at least 50% Activities in Business Plan"
    },
    {
        "id": "53a8dd0335a146a1b1b00dedf6c09aa6",
        "name": "PHC with minimum quality assessment (QA) score of 75% (Biannual)",
        "group": "Quality Improvement",
        "groupKey": "qa",
        "completed": false,
        "indicatorNo": "indicator39",
        "indicatorNational": "indicator39National",
        "indicatorState": "indicator39State",
        "indicatorlga": "indicator39Lga",
        "shortName": "QA Score > 80"
    }
]
